import itertools
import randomForest as rf


def calculate_categories(scores,rate,age):
    # scores = [4,20, 10,40, 2],

    def calculateLetter(num):
        letter = ''
        if num >= 0 and num <= 12:
            letter = 'A'
        elif num >= 13 and num <= 26:
            letter = 'B'
        else:
            letter = 'C'
        return letter

    scoresLetter = tuple([calculateLetter(score) for score in scores])

    book_categories = {
      ('A', 'A', 'A', 'A', 'A'): ['Classics','Picture books', 'Self help'],
      ('A', 'A', 'A', 'A', 'B'): ['Classics', 'Fiction', 'Short Stories'],
      ('A', 'A', 'A', 'A', 'C'): ['Nonfiction', 'Memoir', 'Biography'],
      ('A', 'A', 'A', 'B', 'B'): ['Fiction', 'Contemporary', 'Classics'],
      ('A', 'A', 'A', 'B', 'A'): ['Fantasy', 'Epic Fantasy', 'Short stories'],
      ('A', 'A', 'A', 'B', 'C'): ['Turkish Literature', 'Fiction', 'Classics'],
      ('A', 'A', 'A', 'C', 'C'):['Plays', 'Drama','contemporary'],
      ('A', 'A', 'A', 'C', 'A'): ['Short stories','Picture books', 'dark'],
      ('A', 'A', 'A', 'C', 'B'): ['Spirituality','angels', 'fiction'],
      ('A', 'A', 'B', 'A', 'A'): ['Fantasy', 'Young Adult','comics'],
      ('A', 'A', 'B', 'A', 'B'): ['Nonfiction', 'Memoir', 'Biography'],
      ('A', 'A', 'B', 'A', 'C'): ['Christian Fiction', 'Historical Fiction', 'Christian'],
      ('A', 'A', 'B', 'B', 'B'): ['Romance', 'Fiction', 'Contemporary'],
      ('A', 'A', 'B', 'B', 'A'): ['Paranormal', 'Paranormal Romance', 'Romance'],
      ('A', 'A', 'B', 'B', 'C'): ['Fiction', 'India', 'Travel'],
      ('A', 'A', 'B', 'C', 'C'): ['Historical Fiction', 'Fiction', 'Civil War'],
      ('A', 'A', 'B', 'C', 'A'): ['Christian Fiction', 'Christian', 'Fiction'],
      ('A', 'A', 'B', 'C', 'B'): ['Nonfiction', 'Food', 'Health'],
      ('A', 'A', 'C', 'A', 'A'): ['westerns','Fiction', 'Historical Fiction'],
      ('A', 'A', 'C', 'A', 'B'): ['Biography', 'memoir', 'Nonfiction'],
      ('A', 'A', 'C', 'A', 'C'): ['Classics', 'Fiction', 'Feminism'],
      ('A', 'A', 'C', 'B', 'B'): ['Romance', 'Fiction', 'Contemporary'],
      ('A', 'A', 'C', 'B', 'A'): ['Dystopia','Religion', 'Islam'],
      ('A', 'A', 'C', 'B', 'C'): ['Thriller','Historical Fiction', 'Japan'],
      ('A', 'A', 'C', 'C', 'C'): ['Nonfiction', 'Economics', 'Business'],
      ('A', 'A', 'C', 'C', 'A'): ['Horror','Short stories', 'Vampires'],
      ('A', 'A', 'C', 'C', 'B'): ['German Literature','American History', 'Novels'],
      ('A', 'B', 'A', 'A', 'A'): ['Nature', 'Adventure', 'Contemporary'],
      ('A', 'B', 'A', 'A', 'B'): ['Young Adult', 'Adventure','LGBT'],
      ('A', 'B', 'A', 'A', 'C'): ['Classics','Anthologies', 'Time Travel'],
      ('A', 'B', 'A', 'B', 'B'): ['Travel','Adventure', 'Young Adult'],
      ('A', 'B', 'A', 'B', 'A'): ['Romance', 'Fiction', 'Chick Lit'],
      ('A', 'B', 'A', 'B', 'C'): ['Science Fiction', 'Fiction', 'Fantasy'],
      ('A', 'B', 'A', 'C', 'C'): ['History', 'Nonfiction', 'Military Fiction'],
      ('A', 'B', 'A', 'C', 'A'): ['Nonfiction', 'Business', 'Psychology'],
      ('A', 'B', 'A', 'C', 'B'): ['Chick lit','feminism', 'health'],
      ('A', 'B', 'B', 'A', 'A'): ['Mystery', 'Fiction', 'Classics'],
      ('A', 'B', 'B', 'A', 'B'): ['Fiction', 'Africa', 'South Africa'],
      ('A', 'B', 'B', 'A', 'C'): ['Nonfiction', 'History', 'Science'],
      ('A', 'B', 'B', 'B', 'B'): ['Science', 'Nonfiction', 'Astronomy'],
      ('A', 'B', 'B', 'B', 'A'): ['Thriller', 'Fiction', 'Mystery'],
      ('A', 'B', 'B', 'B', 'C'): ['Classics','Historical Fiction', 'Post apocalyptic'],
      ('A', 'B', 'B', 'C', 'C'): ['Turkish literature','music', 'Fiction'],
      ('A', 'B', 'B', 'C', 'A'): ['Short Stories', 'Fiction', 'Classics'],
      ('A', 'B', 'B', 'C', 'B'): ['Steampunk','India', 'Travel'],
      ('A', 'B', 'C', 'A', 'A'): ['Fantasy', 'Young Adult', 'Fiction'],
      ('A', 'B', 'C', 'A', 'B'): ['Fiction', 'Historical Fiction', 'Vampires'],
      ('A', 'B', 'C', 'A', 'C'): ['Urban Fantasy','Fantasy', 'Writing'],
      ('A', 'B', 'C', 'B', 'B'): ['Science Fiction', 'Post Apocalyptic', 'Classics'],
      ('A', 'B', 'C', 'B', 'A'): ['Historical Fiction', 'Egypt', 'Steampunk'],
      ('A', 'B', 'C', 'B', 'C'): ['Young adult','Christian fiction', 'Literature'],
      ('A', 'B', 'C', 'C', 'C'): ['Nonfiction', 'Economics', 'business'],
      ('A', 'B', 'C', 'C', 'A'): ['Magic','Fantasy', 'Fiction'],
      ('A', 'B', 'C', 'C', 'B'): ['Thriller','Christan', 'Mystery'],
      ('A', 'C', 'A', 'A', 'A'): ['Japan','Fiction', 'Drama'],
      ('A', 'C', 'A', 'A', 'B'): ['Romance','Young Adult', 'Chick Lit'],
      ('A', 'C', 'A', 'A', 'C'): ['Memoir','Biography', 'History'],
      ('A', 'C', 'A', 'B', 'B'): ['Urban fantasy','Fiction', 'Horror'],
      ('A', 'C', 'A', 'B', 'A'): ['Dystopia','Crime', 'Mystery'],
      ('A', 'C', 'A', 'B', 'C'): ['Civil war','history', 'sociology'],
      ('A', 'C', 'A', 'C', 'C'): ['Fiction','Memoir', 'Africa'],
      ('A', 'C', 'A', 'C', 'A'): ['Young adult','Fantasy', 'Zombies'],
      ('A', 'C', 'A', 'C', 'B'): ['Holocaust','History', 'Fiction'],
      ('A', 'C', 'B', 'A', 'A'): ['Young adult','Chick lit', 'Novels'],
      ('A', 'C', 'B', 'A', 'B'): ['Christmas', 'Fiction', 'Childrens'],
      ('A', 'C', 'B', 'A', 'C'): ['Mystery', 'Historical Fiction'],
      ('A', 'C', 'B', 'B', 'B'): ['Nonfiction','Romance', 'Urban Fantasy'],
      ('A', 'C', 'B', 'B', 'A'): ['Self help','Travel', 'Short stories'],
      ('A', 'C', 'B', 'B', 'C'): ['Mythology','Mystery', 'Book Club'],
      ('A', 'C', 'B', 'C', 'C'): ['Science Fiction','Food', 'Magic'],
      ('A', 'C', 'B', 'C', 'A'): ['Plays','Drama', 'Philosophy'],
      ('A', 'C', 'B', 'C', 'B'): ['Classics','Fiction', 'Literary Fiction'],
      ('A', 'C', 'C', 'A', 'A'): ['Classics','Religion', 'Art'],
      ('A', 'C', 'C', 'A', 'B'): ['Classics','Fiction', 'Spirituality'],
      ('A', 'C', 'C', 'A', 'C'): ['Fiction','Literature', 'Anthologies'],
      ('A', 'C', 'C', 'B', 'B'): ['Classics','Poetry', 'Drama'],
      ('A', 'C', 'C', 'B', 'A'): ['Fantasy','Realistic fantasy', 'Science fiction'],
      ('A', 'C', 'C', 'B', 'C'): ['Science','Literature', 'Realistic fiction'],
      ('A', 'C', 'C', 'C', 'C'): ['Urban fantasy','History', 'Thriller'],
      ('A', 'C', 'C', 'C', 'A'): ['Japanese Literature','Novels', 'Literature'],
      ('A', 'C', 'C', 'C', 'B'): ['Fantasy','Japan', 'Fiction'],
      ('B', 'A', 'A', 'A', 'A'): ['Classics','History', 'Adult'],
      ('B', 'A', 'A', 'A', 'B'): ['Urban fantasy','Angels', 'Mythology'],
      ('B', 'A', 'A', 'A', 'C'): ['Dystopia','Survival', 'True crime'],
      ('B', 'A', 'A', 'B', 'B'): ['Poetry','art', 'History'],
      ('B', 'A', 'A', 'B', 'A'): ['Literature','islam', 'Spirituality'],
      ('B', 'A', 'A', 'B', 'C'): ['Turkish literature','Travel', 'Suspense'],
      ('B', 'A', 'A', 'C', 'C'): ['Poetry','Classics', 'Japan'],
      ('B', 'A', 'A', 'C', 'A'): ['Romance','Science', 'Nonfictiom'],
      ('B', 'A', 'A', 'C', 'B'): ['Mystery','Magic', 'Suspense'],
      ('B', 'A', 'B', 'A', 'A'): ['Suspense','Post apocalyptic', 'Fiction'],
      ('B', 'A', 'B', 'A', 'B'): ['True crime','Horror', 'Fiction'],
      ('B', 'A', 'B', 'A', 'C'): ['Time travel', 'Science fiction', 'Contemporary'],
      ('B', 'A', 'B', 'B', 'B'): ['Classics', 'Fiction', 'France'],
      ('B', 'A', 'B', 'B', 'A'): ['Fiction', 'Classics', 'Adventure'],
      ('B', 'A', 'B', 'B', 'C'): ['Fiction', 'Historical Fiction', 'Africa'],
      ('B', 'A', 'B', 'C', 'C'): ['Science','History', 'Fiction'],
      ('B', 'A', 'B', 'C', 'A'): ['Novels','Young adult', 'New adult'],
      ('B', 'A', 'B', 'C', 'B'): ['Thriller', 'Fiction', 'Mystery'],
      ('B', 'A', 'C', 'A', 'A'): ['Comics','Young adult', 'Fiction'],
      ('B', 'A', 'C', 'A', 'B'): ['Humor','Fantasy', 'Fiction'],
      ('B', 'A', 'C', 'A', 'C'): ['Travel', 'romance', 'Fantasy'],
      ('B', 'A', 'C', 'B', 'B'): ['Classics','Fiction', 'Adventure'],
      ('B', 'A', 'C', 'B', 'A'): ['Fiction','Humor', 'Fantasy'],
      ('B', 'A', 'C', 'B', 'C'): ['Fantasy','Psychology', 'Christian'],
      ('B', 'A', 'C', 'C', 'C'): ['American','History', 'Westerns'],
      ('B', 'A', 'C', 'C', 'A'): ['Contemporary','Romance', 'Fiction'],
      ('B', 'A', 'C', 'C', 'B'): ['Romance','Nonfiction', 'Inspirational'],
      ('B', 'B', 'A', 'A', 'A'): ['Ficiton','Graphic novels manga', 'manga'],
      ('B', 'B', 'A', 'A', 'B'): ['Literature','Young adult', 'Chick lit'],
      ('B', 'B', 'A', 'A', 'C'): ['Fiction','Military fiction', 'history'],
      ('B', 'B', 'A', 'B', 'B'): ['Dark','Epic fantasy', 'Fiction'],
      ('B', 'B', 'A', 'B', 'A'): ['Romance','Religion', 'Literature'],
      ('B', 'B', 'A', 'B', 'C'): ['British literature','Dictionaries', 'Bagladesh'],
      ('B', 'B', 'A', 'C', 'C'): ['Westerns','Business', 'Science fiction'],
      ('B', 'B', 'A', 'C', 'A'): ['Classics','Russia', 'Inspirational'],
      ('B', 'B', 'A', 'C', 'B'): ['Contemporary','Nonfiction', 'Psychology'],
      ('B', 'B', 'B', 'A', 'A'): ['Classics', 'Fiction', 'Horror'],
      ('B', 'B', 'B', 'A', 'B'): ['Historical fiction','Young adult', 'History'],
      ('B', 'B', 'B', 'A', 'C'): ['France','Fantasy', 'Literature'],
      ('B', 'B', 'B', 'B', 'B'): ['Philosophy', 'Religion', 'Historical Fiction'],
      ('B', 'B', 'B', 'B', 'A'): ['Graphic novels','Short stories', 'Dark'],
      ('B', 'B', 'B', 'B', 'C'): ['Dystopia','Fiction', 'Thriller'],
      ('B', 'B', 'B', 'C', 'C'): ['Young adult ','science fiction', 'fiction'],
      ('B', 'B', 'B', 'C', 'A'): ['Picture book','Graphic novels', 'Audiobook'],
      ('B', 'B', 'B', 'C', 'B'): ['Dystopia', 'Fantasy', 'Romance'],
      ('B', 'B', 'C', 'A', 'A'): ['Biography','Gaming', 'Memoir'],
      ('B', 'B', 'C', 'A', 'B'): ['Romance','Paranormal', 'Paranormal romance'],
      ('B', 'B', 'C', 'A', 'C'): ['Young adult','Nature', 'Classics'],
      ('B', 'B', 'C', 'B', 'B'): ['Fiction','Fairy tale', 'Literature'],
      ('B', 'B', 'C', 'B', 'A'): ['Science fiction','Fantasy', 'Religion'],
      ('B', 'B', 'C', 'B', 'C'): ['History','Nature', 'American'],
      ('B', 'B', 'C', 'C', 'C'): ['Mystery','Fantasy', 'Vampires'],
      ('B', 'B', 'C', 'C', 'A'): ['Graphic novels','Short stories', 'Self Help'],
      ('B', 'B', 'C', 'C', 'B'): ['Epic','feminism', 'Literature'],
      ('B', 'B', 'C', 'A', 'A'): ['Manga','Realistic Fiction', 'Audiobook'],
      ('B', 'B', 'C', 'A', 'B'): ['Poetry','Historical ficiton', 'History'],
      ('B', 'B', 'C', 'A', 'C'): ['Romance','Drama', 'Art'],
      ('B', 'B', 'C', 'B', 'B'): ['Fantasy','Classics', 'Comics'],
      ('B', 'B', 'C', 'B', 'A'): ['Nonfiction', 'Adult', 'Audiobook'],
      ('B', 'B', 'C', 'B', 'C'): ['Novels', 'Contemporary', 'Literature'],
      ('B', 'B', 'C', 'C', 'C'): ['Adventure', 'Travel', 'Africa'],
      ('B', 'B', 'C', 'C', 'A'): ['Classics',' southern',' adventure'],
      ('B', 'B', 'C', 'C', 'B'): ['Feminism', 'Young Adult', 'Contemporary'],
      ('B', 'C', 'B', 'A', 'A'): ['Literature', 'School', 'Middle Grade'],
      ('B', 'C', 'B', 'A', 'B'): ['Romance', 'New adult', 'Mystery'],
      ('B', 'C', 'B', 'A', 'C'): ['Young Adult', 'Nonfiction', 'Fiction'],
      ('B', 'C', 'B', 'B', 'B'): ['Romance', 'Fiction', 'Contemporary'],
      ('B', 'C', 'B', 'B', 'A'): ['Travel','Novels', 'Africa'],
      ('B', 'C', 'B', 'B', 'C'): ['Fantasy','Historical fiction', 'Civil war'],
      ('B', 'C', 'B', 'C', 'C'): ['Sociology','Philosophy', 'Fiction'],
      ('B', 'C', 'B', 'C', 'A'): ['Classics','Anthologies', 'Novels'],
      ('B', 'C', 'B', 'C', 'B'): ['Fiction','Angels', 'History'],
      ('B', 'C', 'C', 'A', 'A'): ['Chick Lit', 'Romance', 'Short stories'],
      ('B', 'C', 'C', 'A', 'B'): ['Romance', 'Erotica', 'Fiction'],
      ('B', 'C', 'C', 'A', 'C'): ['Historical fantasy','Christian fiction', 'Fiction'],
      ('B', 'C', 'C', 'B', 'B'): ['Fiction','History', 'Southern'],
      ('B', 'C', 'C', 'B', 'A'): ['Romance', 'Magical Realism', 'Fiction'],
      ('B', 'C', 'C', 'B', 'C'): ['Crime','France', 'war'],
      ('B', 'C', 'C', 'C', 'C'): ['Science','Science fiction', 'Fiction'],
      ('B', 'C', 'C', 'C', 'A'): ['Historical','Novels', 'Fiction'],
      ('B', 'C', 'C', 'C', 'B'): ['Philosophy','classics', 'school'],
      ('C', 'A', 'A', 'A', 'A'): ['Dark','Paranormal', 'suspense'],
      ('C', 'A', 'A', 'A', 'B'): ['Epic fantasy','Spirituality', 'Christian'],
      ('C', 'A', 'A', 'A', 'C'): ['Literature','Classics', 'Nonfiction'],
      ('C', 'A', 'A', 'B', 'B'): ['Memoir','Travel', 'Africa'],
      ('C', 'A', 'A', 'B', 'A'): ['Manga','Romance', 'Novels'],
      ('C', 'A', 'A', 'B', 'C'): ['Historical fiction','Civil war', 'War'],
      ('C', 'A', 'A', 'C', 'C'): ['Classics', 'Fiction', 'Feminism'],
      ('C', 'A', 'A', 'C', 'A'): ['Paranormal','True crime', 'Young adult'],
      ('C', 'A', 'A', 'C', 'B'): ['Africa','Fiction', 'Travel'],
      ('C', 'A', 'B', 'A', 'A'): ['Classics','Novels', 'Literature'],
      ('C', 'A', 'B', 'A', 'B'): ['Plays','Drama', 'Poetry'],
      ('C', 'A', 'B', 'A', 'C'): ['Romance','Classics', 'Westerns'],
      ('C', 'A', 'B', 'B', 'B'): ['Romance','French literature', 'France'],
      ('C', 'A', 'B', 'B', 'A'): ['Fiction','France', 'Dragons'],
      ('C', 'A', 'B', 'B', 'C'): ['Novels','Irish literature', 'Ireland'],
      ('C', 'A', 'B', 'C', 'C'): ['Mystery','Horror', 'Thriller'],
      ('C', 'A', 'B', 'C', 'A'): ['Science','Memoir', 'Food'],
      ('C', 'A', 'B', 'C', 'B'): ['Nonfiction','Contemporary', 'Nature'],
      ('C', 'A', 'C', 'A', 'A'): ['Suspense','Spirituality', 'Religion'],
      ('C', 'A', 'C', 'A', 'B'): ['Dystopia','Paranormal romance', 'Art'],
      ('C', 'A', 'C', 'A', 'C'): ['Nonfiction','Childrens', 'Parenting'],
      ('C', 'A', 'C', 'B', 'B'): ['Epic','Contemporary', 'Mythology'],
      ('C', 'A', 'C', 'B', 'A'): ['Romance','Classics', 'Chick lit'],
      ('C', 'A', 'C', 'B', 'C'): ['New adult','Fiction', 'Japanese literature'],
      ('C', 'A', 'C', 'C', 'C'): ['Survival','Travel', 'Business'],
      ('C', 'A', 'C', 'C', 'A'): ['Vampires','Fantasy', 'Angels'],
      ('C', 'A', 'C', 'C', 'B'): ['Science fiction','Romance', 'Epic fantasy'],
      ('C', 'B', 'A', 'A', 'A'): ['Thriller','Mystery', 'dystopia'],
      ('C', 'B', 'A', 'A', 'B'): ['Nature','Contemporary', 'Novels'],
      ('C', 'B', 'A', 'A', 'C'): ['Fairy tales','fantasy', 'Vampires'],
      ('C', 'B', 'A', 'B', 'B'): ['Science','Mathematics', 'Music'],
      ('C', 'B', 'A', 'B', 'A'): ['Manga', 'Graphic novels', 'Humor'],
      ('C', 'B', 'A', 'B', 'C'): ['Military fiction','Hisrtory', 'War'],
      ('C', 'B', 'A', 'C', 'C'): ['Horror','Fantasy', 'Mystery'],
      ('C', 'B', 'A', 'C', 'A'): ['Fiction', 'Novels', 'Spirituality'],
      ('C', 'B', 'A', 'C', 'B'): ['Religion', 'Nonfiction', 'Lds'],
      ('C', 'B', 'B', 'A', 'A'): ['New adult','Nonfiction', 'Novels'],
      ('C', 'B', 'B', 'A', 'B'): ['Fantasy','Young adult', 'Contemporary'],
      ('C', 'B', 'B', 'A', 'C'): ['Literature','Vampires', 'Fantasy'],
      ('C', 'B', 'B', 'B', 'B'): ['Fantasy','Gaming', 'Christian'],
      ('C', 'B', 'B', 'B', 'A'): ['Graphic novels','Fantasy', 'Drawing'],
      ('C', 'B', 'B', 'B', 'C'): ['Poetry','Plays', 'Art'],
      ('C', 'B', 'B', 'C', 'C'): ['Young Adult', 'Romance', 'Contemporary'],
      ('C', 'B', 'B', 'C', 'A'): ['Young adult','contemporary', 'Book club'],
      ('C', 'B', 'B', 'C', 'B'): ['Fiction','lds', 'christian'],
      ('C', 'B', 'C', 'A', 'A'): ['Chick Lit','Science Fiction', 'Dystopia'],
      ('C', 'B', 'C', 'A', 'B'): ['Fiction', 'Philosophy', 'Fantasy'],
      ('C', 'B', 'C', 'A', 'C'): ['Fiction','Russia', 'Philosophy'],
      ('C', 'B', 'C', 'B', 'B'): ['Romance','Young adult', 'epic'],
      ('C', 'B', 'C', 'B', 'A'): ['Young adult','Fantasy', 'Epic fantasy'],
      ('C', 'B', 'C', 'B', 'C'): ['Historical','Historical fiction', 'Russia'],
      ('C', 'B', 'C', 'C', 'C'): ['Novels','Plays', 'American'],
      ('C', 'B', 'C', 'C', 'A'): ['Dragons','Magic', 'Dark'],
      ('C', 'B', 'C', 'C', 'B'): ['Literature','Contemporary', 'school'],
      ('C', 'B', 'C', 'A', 'A'): ['Adventure','Dystopia', 'New Adult'],
      ('C', 'B', 'C', 'A', 'B'): ['Contemporary','Romance', 'Fiction'],
      ('C', 'B', 'C', 'A', 'C'): ['Classics','Urban fantasy', 'Civil war'],
      ('C', 'B', 'C', 'B', 'B'): ['Turkish literature','Fantasy', 'Romance'],
      ('C', 'B', 'C', 'B', 'A'): ['True crime','History', 'Fiction'],
      ('C', 'B', 'C', 'B', 'C'): ['Fictiom','Epic fantasy', 'Feminism'],
      ('C', 'B', 'C', 'C', 'C'): ['Literature','Drama', 'Spirituality'],
      ('C', 'B', 'C', 'C', 'A'): ['Classics','Japan', 'Japanese Literature'],
      ('C', 'B', 'C', 'C', 'B'): ['History','France', 'Suspense'],
      ('C', 'C', 'B', 'A', 'A'): ['Graphic novels manga','contemporary', 'Epic'],
      ('C', 'C', 'B', 'A', 'B'): ['Thriller','Southern', 'egypt'],
      ('C', 'C', 'B', 'A', 'C'): ['Classics', 'Fiction', 'Feminism'],
      ('C', 'C', 'B', 'B', 'B'): ['Nonfiction','Theathre', 'Fantasy'],
      ('C', 'C', 'B', 'B', 'A'): ['Realistic fiction','Fiction', 'Romance'],
      ('C', 'C', 'B', 'B', 'C'): ['Fiction','Philosophy', 'Art'],
      ('C', 'C', 'B', 'C', 'C'): ['Bipgraphy','Music', 'Adult'],
      ('C', 'C', 'B', 'C', 'A'): ['Fiction','Humor', 'Religion'],
      ('C', 'C', 'B', 'C', 'B'): ['New Adult','Adventure', 'Thriller'],
      ('C', 'C', 'C', 'A', 'A'): ['Religion','Poetry', 'islam'],
      ('C', 'C', 'C', 'A', 'B'): ['American','Civil war', 'Japan'],
      ('C', 'C', 'C', 'A', 'C'): ['Westerns','American', 'War'],
      ('C', 'C', 'C', 'B', 'B'): ['Classics','Novels', 'Historys'],
      ('C', 'C', 'C', 'B', 'A'): ['Humor','Contemporary', 'Picture books'],
      ('C', 'C', 'C', 'B', 'C'): ['Survival','Adventure', 'School'],
      ('C', 'C', 'C', 'C', 'C'): ['Science Fiction', 'Historical fiction', 'Survival'],
      ('C', 'C', 'C', 'C', 'A'): ['Science Fiction', 'Fiction', 'Writing'],
      ('C', 'C', 'C', 'C', 'B'): ['Nonfiction','Business', 'Psychology'],
    }
    possible_combinations = itertools.product('ABC', repeat=len(scoresLetter))

    for combination in possible_combinations:
        if all(combination[i] == scoresLetter[i] for i in range(len(scoresLetter))):
            print((book_categories[combination]))
            return rf.randomForest((book_categories[combination]),rate,age)
