import itertools
import randomForest as rf


def calculate_categories(scores,rate):
    # scores = [4,20, 10,40, 2],

    def calculateLetter(num):
        letter = ''
        if num >= 0 and num <= 12:
            letter = 'A'
        elif num >= 13 and num <= 26:
            letter = 'B'
        else:
            letter = 'C'
        return letter

    scoresLetter = tuple([calculateLetter(score) for score in scores])

    book_categories = {
        ('A', 'A', 'A', 'A', 'A'): ['Growth Mindset', 'Short stories', 'Self Help'],
        ('A', 'A', 'A', 'A', 'B'): ['Ireland', 'Spy thriller', 'Roman'],
        ('A', 'A', 'A', 'A', 'C'): ['Comic book', 'Russian literature', 'How to'],
        ('A', 'A', 'A', 'B', 'B'): ['International Literature', 'mental health', 'diary'],
        ('A', 'A', 'A', 'B', 'A'): ['Clean Romance', 'Prayer', 'drawing'],
        ('A', 'A', 'A', 'B', 'C'): ['Human Development', 'Short stories', 'Self Help'],
        ('A', 'A', 'A', 'C', 'C'): ['Relationships', 'cookbooks', 'classics'],
        ('A', 'A', 'A', 'C', 'A'): ['Short stories', 'plants', 'ecology'],
        ('A', 'A', 'A', 'C', 'B'): ['Spirituality', 'cats', 'fiction'],
        ('A', 'A', 'B', 'A', 'A'): ['Fantasy Romance', 'Punk', 'Americana'],
        ('A', 'A', 'B', 'A', 'B'): ['Biography', 'Japanese history', 'Church'],
        ('A', 'A', 'B', 'A', 'C'): ['Speculative Fiction', 'frugal', 'medicine'],
        ('A', 'A', 'B', 'B', 'B'): ['Time Travel Romance', 'Russia', 'College'],
        ('A', 'A', 'B', 'B', 'A'): ['Pop Culture', 'Scotland', 'Comedian'],
        ('A', 'A', 'B', 'B', 'C'): ['Multicultural Literature', 'Russian revolution', 'Belgium'],
        ('A', 'A', 'B', 'C', 'C'): ['Nobel Prize', 'Architecture', 'Physics'],
        ('A', 'A', 'B', 'C', 'A'): ['Polish literature', 'Business', 'Palaeontology'],
        ('A', 'A', 'B', 'C', 'B'): ['Sociology', 'Food writing', 'Economics'],
        ('A', 'A', 'C', 'A', 'A'): ['Western historical romance', 'Theosophy', 'Folklore'],
        ('A', 'A', 'C', 'A', 'B'): ['Biography memoir', 'biography', 'Sports'],
        ('A', 'A', 'C', 'A', 'C'): ['Journalism', 'Womens ficiton', 'Home school'],
        ('A', 'A', 'C', 'B', 'B'): ['Interracial romance', 'Back to school', 'Genetics'],
        ('A', 'A', 'C', 'B', 'A'): ['Buddhism', 'Ghost stories', 'India'],
        ('A', 'A', 'C', 'B', 'C'): ['Hungarian literature', 'Hungary', 'Chinese medicine'],
        ('A', 'A', 'C', 'C', 'C'): ['Philosophy', 'Sociology', 'Mathematics'],
        ('A', 'A', 'C', 'C', 'A'): ['Moroccan', 'Short stories', 'Climate change fiction'],
        ('A', 'A', 'C', 'C', 'B'): ['Cultural', 'Native American history', 'Occult'],
        ('A', 'B', 'A', 'A', 'A'): ['Female authors', 'poverty', 'sweden'],
        ('A', 'B', 'A', 'A', 'B'): ['Fan fiction', 'Fandom', 'Hungary'],
        ('A', 'B', 'A', 'A', 'C'): ['Modern classics', 'Anthologies', 'Fat studies'],
        ('A', 'B', 'A', 'B', 'B'): ['Travelogue', 'Travel', 'Road trip'],
        ('A', 'B', 'A', 'B', 'A'): ['Fiction', 'Intelligent design', 'Forgotten realms'],
        ('A', 'B', 'A', 'B', 'C'): ['Singularity', 'History of science', 'Global warming'],
        ('A', 'B', 'A', 'C', 'C'): ['Historical mystery', 'illness', 'Military science fiction'],
        ('A', 'B', 'A', 'C', 'A'): ['Social', 'Short stories', 'Sociology'],
        ('A', 'B', 'A', 'C', 'B'): ['Female authors', 'Vegetarianism', 'Railways'],
        ('A', 'B', 'B', 'A', 'A'): ['Travel', 'Road trip', 'Guidebook'],
        ('A', 'B', 'B', 'A', 'B'): ['Art', 'Art history', 'Pulp'],
        ('A', 'B', 'B', 'A', 'C'): ['Productivity', 'Batman', 'Detective'],
        ('A', 'B', 'B', 'B', 'B'): ['Astronomy', 'Anarchism', 'Teachers'],
        ('A', 'B', 'B', 'B', 'A'): ['Female authors', 'disability', 'esoterica'],
        ('A', 'B', 'B', 'B', 'C'): ['French revolution', 'Witchcraft', 'Climate change'],
        ('A', 'B', 'B', 'C', 'C'): ['Turkish', 'Games', 'Hip Hop'],
        ('A', 'B', 'B', 'C', 'A'): ['Fantasy romance', 'School stories', 'Christian contemporary fiction'],
        ('A', 'B', 'B', 'C', 'B'): ['Asian literature', 'Japanese literature', 'Mozambique'],
        ('A', 'B', 'C', 'A', 'A'): ['Latin American literature', 'Media tie in', 'Anthrop'],
        ('A', 'B', 'C', 'A', 'B'): ['Dark', 'Liberia', 'Italy'],
        ('A', 'B', 'C', 'A', 'C'): ['Roman', 'Star trek', 'English literature'],
        ('A', 'B', 'C', 'B', 'B'): ['War', 'Ukraine', 'The Americas'],
        ('A', 'B', 'C', 'B', 'A'): ['Ancient history', 'steampunk', 'Womens'],
        ('A', 'B', 'C', 'B', 'C'): ['Young adult', 'Christian historical ficrion', 'pilots'],
        ('A', 'B', 'C', 'C', 'C'): ['Supernatural romance', 'nursery rhymes', 'sports romance'],
        ('A', 'B', 'C', 'C', 'A'): ['Novella', 'black literature', 'Psychiatry'],
        ('A', 'B', 'C', 'C', 'B'): ['Thriller', 'Christanity', 'holocaust'],
        ('A', 'C', 'A', 'A', 'A'): ['Chinese literature', 'Buses', 'Ethiopia'],
        ('A', 'C', 'A', 'A', 'B'): ['Regency', 'art design', 'Science fiction romance'],
        ('A', 'C', 'A', 'A', 'C'): ['Usability', 'Horses', 'Canada'],
        ('A', 'C', 'A', 'B', 'B'): ['Urban', 'Italian literature', 'Battle of britain'],
        ('A', 'C', 'A', 'B', 'A'): ['Traditional regency', 'Harlequin romance', 'Ghosts'],
        ('A', 'C', 'A', 'B', 'C'): ['Civil war history', 'International development', 'Social science'],
        ('A', 'C', 'A', 'C', 'C'): ['Low fantasy', 'Norman', 'African literature'],
        ('A', 'C', 'A', 'C', 'A'): ['Czech literature', 'Soccer', 'Zombies'],
        ('A', 'C', 'A', 'C', 'B'): ['Indonesian literature ', 'Short stories', 'Self Help'],
        ('A', 'C', 'B', 'A', 'A'): ['Juvenile', 'Chick lit', 'animal fiction'],
        ('A', 'C', 'B', 'A', 'B'): ['Travel', 'Christmas', 'Star trek original series'],
        ('A', 'C', 'B', 'A', 'C'): ['Historical fantasy', 'Discipleship', 'Arthurian'],
        ('A', 'C', 'B', 'B', 'B'): ['Society', 'Star wars', 'Ornithology'],
        ('A', 'C', 'B', 'B', 'A'): ['Golden age mystery', 'Emergency services', 'Trivia'],
        ('A', 'C', 'B', 'B', 'C'): ['Naval historical fiction', 'Maritime', 'website design'],
        ('A', 'C', 'B', 'C', 'C'): ['Fae', 'Culinary', 'Magic'],
        ('A', 'C', 'B', 'C', 'A'): ['Personal development', 'Money', 'Football'],
        ('A', 'C', 'B', 'C', 'B'): ['Urbanism', 'Star trek deep space nine', 'christian'],
        ('A', 'C', 'C', 'A', 'A'): ['Harlequin heartwarming', 'mixed martial arts', 'halloween'],
        ('A', 'C', 'C', 'A', 'B'): ['Cryptozoology', 'Gaming', 'Harlequin presents'],
        ('A', 'C', 'C', 'A', 'C'): ['Creation science', 'Academia', 'Anthrop'],
        ('A', 'C', 'C', 'B', 'B'): ['Space opera', 'Sustainability', 'Post colonial'],
        ('A', 'C', 'C', 'B', 'A'): ['Sci fi fantasy', 'Geek', 'figure skating'],
        ('A', 'C', 'C', 'B', 'C'): ['Political science', 'Romanian literature', 'Earth sciences'],
        ('A', 'C', 'C', 'C', 'C'): ['Urban fantasy', 'Spanish history', 'Doctors'],
        ('A', 'C', 'C', 'C', 'A'): ['Chinese literature', 'Algebra', 'Geography'],
        ('A', 'C', 'C', 'C', 'B'): ['Alternate history', 'Fat acceptance', 'Republic of the congo'],
        ('B', 'A', 'A', 'A', 'A'): ['Cult classics', 'Aircraft', 'Electrical engineering'],
        ('B', 'A', 'A', 'A', 'B'): ['Low fantasy books', 'Mountaineering', 'Nazi party'],
        ('B', 'A', 'A', 'A', 'C'): ['Read for college', 'Teaching', 'Scripture'],
        ('B', 'A', 'A', 'B', 'B'): ['Art and photography', 'art', 'art history'],
        ('B', 'A', 'A', 'B', 'A'): ['Hungarian literature', 'Judaism', ' 3th century'],
        ('B', 'A', 'A', 'B', 'C'): ['Hinduism', 'Christian fiction', 'Ethnography'],
        ('B', 'A', 'A', 'C', 'C'): ['Government', 'Viking romance', 'Military fiction'],
        ('B', 'A', 'A', 'C', 'A'): ['Regency romance', 'regency', 'Womens studies'],
        ('B', 'A', 'A', 'C', 'B'): ['Microhistory', 'Harlequin historical', 'Semiotics'],
        ('B', 'A', 'B', 'A', 'A'): ['Romantic suspense', 'Post apocalyptic', 'Reference'],
        ('B', 'A', 'B', 'A', 'B'): ['True crime', 'Wonder woman', 'Labor'],
        ('B', 'A', 'B', 'A', 'C'): ['Southern', 'Sao tome and principe', 'Mali'],
        ('B', 'A', 'B', 'B', 'B'): ['Books about books', 'History of medicine', 'Apple'],
        ('B', 'A', 'B', 'B', 'A'): ['Comic fantasy', 'Fundamentalism', 'Star trek voyager'],
        ('B', 'A', 'B', 'B', 'C'): ['Cultural studies', ' 5th century', 'healthcare'],
        ('B', 'A', 'B', 'C', 'C'): ['Academic', 'European history', 'Conspiracy theories'],
        ('B', 'A', 'B', 'C', 'A'): ['Novella', 'Ghana', 'Georgian'],
        ('B', 'A', 'B', 'C', 'B'): ['Lenin', 'African american', 'Led zeppelin'],
        ('B', 'A', 'C', 'A', 'A'): ['Cartoon', 'Role playing games', 'Weird west'],
        ('B', 'A', 'C', 'A', 'B'): ['Comedy', 'Herbs', 'Witches'],
        ('B', 'A', 'C', 'A', 'C'): ['Time travelTime travel romance', 'Motorcycling'],
        ('B', 'A', 'C', 'B', 'B'): ['American fiction', 'Soviet union', 'Hackers'],
        ('B', 'A', 'C', 'B', 'A'): ['Jokes', 'Humor', 'Aliens'],
        ('B', 'A', 'C', 'B', 'C'): ['Psychoanalysis', 'Psychology', 'Christian fiction'],
        ('B', 'A', 'C', 'C', 'C'): ['American history', 'The united states of america', 'American revolution'],
        ('B', 'A', 'C', 'C', 'A'): ['Contemporary romance', 'Roman', 'Contemporary'],
        ('B', 'A', 'C', 'C', 'B'): ['Futuristic romance', 'Futurism', 'Aviation'],
        ('B', 'B', 'A', 'A', 'A'): ['Webcomic', 'Graphic novels manga', 'manga'],
        ('B', 'B', 'A', 'A', 'B'): ['Swedish literature', 'Agriculture', 'Central africa'],
        ('B', 'B', 'A', 'A', 'C'): ['Journaling', 'Journalism', 'Nigeria'],
        ('B', 'B', 'A', 'B', 'B'): ['Noir', 'Catholic', 'Fighters'],
        ('B', 'B', 'A', 'B', 'A'): ['Love', 'Harlequin teen', 'Libya'],
        ('B', 'B', 'A', 'B', 'C'): ['British literature', 'Dictionaries', 'Bagladesh'],
        ('B', 'B', 'A', 'C', 'C'): ['Western romance', 'Personal finance', 'Bolivia'],
        ('B', 'B', 'A', 'C', 'A'): ['Canadian literature', 'Nursing', 'Holiday'],
        ('B', 'B', 'A', 'C', 'B'): ['International relations', 'International', 'Zimbabwe'],
        ('B', 'B', 'B', 'A', 'A'): ['Cultural heritage', 'Amazon', 'Georgian romance'],
        ('B', 'B', 'B', 'A', 'B'): ['Young adults historical fiction', 'Parenting', 'Far right'],
        ('B', 'B', 'B', 'A', 'C'): ['Tragedy', 'Law', 'Portugal'],
        ('B', 'B', 'B', 'B', 'B'): ['Theology', 'Pop Culture', 'Historical Fiction'],
        ('B', 'B', 'B', 'B', 'A'): ['Graphic novels', 'Horse racing', 'World of darkness'],
        ('B', 'B', 'B', 'B', 'C'): ['Utopia', 'Software', 'Algeria'],
        ('B', 'B', 'B', 'C', 'C'): ['Young adult science fiction', 'young adult', 'sword and sorcery'],
        ('B', 'B', 'B', 'C', 'A'): ['Picture book', 'Wine', 'Anthropology'],
        ('B', 'B', 'B', 'C', 'B'): ['Anthologies', 'Plants', 'Goddess'],
        ('B', 'B', 'C', 'A', 'A'): ['Slice of life', 'Gamebooks', 'Ancient'],
        ('B', 'B', 'C', 'A', 'B'): ['Southern gothic', 'Paranormal', 'Self Help'],
        ('B', 'B', 'C', 'A', 'C'): [' 7th century', 'Birds', 'Sword and planet'],
        ('B', 'B', 'C', 'B', 'B'): ['Emotion', 'Fairies', 'Did not finish'],
        ('B', 'B', 'C', 'B', 'A'): ['Science fiction fantasy', 'Evangelism', 'World of warcraft'],
        ('B', 'B', 'C', 'B', 'C'): ['Natural history', 'Evolution', 'American classic'],
        ('B', 'B', 'C', 'C', 'C'): ['Cozy mystery', 'Spanish literature', 'Jewellery'],
        ('B', 'B', 'C', 'C', 'A'): ['Graphic novels comics', 'Short stories', 'Self Help'],
        ('B', 'B', 'C', 'C', 'B'): ['Pop culture', 'Australia', 'Cuisine'],
        ('B', 'B', 'C', 'A', 'A'): ['Manga', 'Disease', 'Morocco'],
        ('B', 'B', 'C', 'A', 'B'): ['Love inspired', 'Spain', 'Latin American history'],
        ('B', 'B', 'C', 'A', 'C'): ['Love inspired historical', 'Drama', 'Visual art'],
        ('B', 'B', 'C', 'B', 'B'): ['Finnish literature', 'English civil war', 'Disability studies'],
        ('B', 'B', 'C', 'B', 'A'): ['Field guides', 'Travel', 'Novella'],
        ('B', 'B', 'C', 'B', 'C'): ['Novels', 'transport', 'Artificial Intelligence'],
        ('B', 'B', 'C', 'C', 'C'): ['Adventure', 'Action', 'Algeria'],
        ('B', 'B', 'C', 'C', 'A'): ['Cult classics', ' western africa', ' airships'],
        ('B', 'B', 'C', 'C', 'B'): ['Education', 'teaching', 'dictionaries'],
        ('B', 'C', 'B', 'A', 'A'): ['Epic poetry', 'epic fantasy', 'poetry'],
        ('B', 'C', 'B', 'A', 'B'): ['Gothic romance', 'chemistry', 'egyptology'],
        ('B', 'C', 'B', 'A', 'C'): ['Classical studies', 'romania', 'tanzania'],
        ('B', 'C', 'B', 'B', 'B'): ['Popular science', 'Holland', 'Beer'],
        ('B', 'C', 'B', 'B', 'A'): ['Comic book', 'Novella', 'Albanian literature'],
        ('B', 'C', 'B', 'B', 'C'): ['International', 'Librarianship', 'Coding'],
        ('B', 'C', 'B', 'C', 'C'): ['Social', '  th century', 'Dying Earth'],
        ('B', 'C', 'B', 'C', 'A'): ['Cult classics', 'Anthologies', 'Light novel'],
        ('B', 'C', 'B', 'C', 'B'): ['Futurism', 'Angels', 'Soviet history'],
        ('B', 'C', 'C', 'A', 'A'): ['Modern', 'Guides', 'Chess'],
        ('B', 'C', 'C', 'A', 'B'): ['Cryptids', 'Reportage', 'Faith'],
        ('B', 'C', 'C', 'A', 'C'): ['Historical fantasy', 'Poland', 'Banking'],
        ('B', 'C', 'C', 'B', 'B'): ['High fantasy', 'Medieval history', 'Wizards'],
        ('B', 'C', 'C', 'B', 'A'): ['Psychological thriller', 'Pirates', 'Gothic'],
        ('B', 'C', 'C', 'B', 'C'): ['Crime', 'France', 'American revolutionary war'],
        ('B', 'C', 'C', 'C', 'C'): ['Science', 'Bulgaria', ' 9th century'],
        ('B', 'C', 'C', 'C', 'A'): ['Ghost stories', 'Grad school', 'Monsters'],
        ('B', 'C', 'C', 'C', 'B'): ['Eastern philosophy', 'web', 'teaching'],
        ('C', 'A', 'A', 'A', 'A'): ['Death', 'Paramedics', 'Astrology'],
        ('C', 'A', 'A', 'A', 'B'): ['Epic', 'Foster children', 'Mormonism'],
        ('C', 'A', 'A', 'A', 'C'): ['Near future', 'Church history', 'Biology'],
        ('C', 'A', 'A', 'B', 'B'): ['Memoir', 'Trains', 'Northern Africa'],
        ('C', 'A', 'A', 'B', 'A'): ['Manga romance', 'Taoism', 'Newyork'],
        ('C', 'A', 'A', 'B', 'C'): ['Victorian', 'Civil war', 'Presidents'],
        ('C', 'A', 'A', 'C', 'C'): ['Theory', 'Gastronomy', 'Google'],
        ('C', 'A', 'A', 'C', 'A'): ['Deception', 'Scandinavian literature', 'Young adult paranormal'],
        ('C', 'A', 'A', 'C', 'B'): ['Biography memoir', 'Africa', 'Road trip'],
        ('C', 'A', 'B', 'A', 'A'): ['Communication', 'Greece', 'Irish literature'],
        ('C', 'A', 'B', 'A', 'B'): ['Plays', 'Nutrition', 'Robots'],
        ('C', 'A', 'B', 'A', 'C'): ['Romance', 'Danish', 'Westerns'],
        ('C', 'A', 'B', 'B', 'B'): ['Love inspired suspense', ' 0th century', 'Students'],
        ('C', 'A', 'B', 'B', 'A'): ['French literature', 'Fitness', 'Dragons'],
        ('C', 'A', 'B', 'B', 'C'): ['Logic', 'Atlases', 'Linguistics'],
        ('C', 'A', 'B', 'C', 'C'): ['Murder mystery', 'Magick', 'Wildlife'],
        ('C', 'A', 'B', 'C', 'A'): ['2 st century', 'Horror', 'Cooking'],
        ('C', 'A', 'B', 'C', 'B'): ['Mystery thriller', 'Conservation', 'Outdoors'],
        ('C', 'A', 'C', 'A', 'A'): ['Suspense', 'Divorce', 'Divination'],
        ('C', 'A', 'C', 'A', 'B'): ['Dystopia', 'Paranormal romance', 'Martial arts'],
        ('C', 'A', 'C', 'A', 'C'): ['Cultural', 'Virtual reality', 'Foster parents'],
        ('C', 'A', 'C', 'B', 'B'): ['Retellings', 'Ukranian literature', 'Islam'],
        ('C', 'A', 'C', 'B', 'A'): ['Love story', 'Egytian literature', ' 2th century'],
        ('C', 'A', 'C', 'B', 'C'): ['Inspirational', 'Unfinished', 'Fostering'],
        ('C', 'A', 'C', 'C', 'C'): ['Survival', 'Computer science', 'Maritime'],
        ('C', 'A', 'C', 'C', 'A'): ['Espionage', 'Film', 'God'],
        ('C', 'A', 'C', 'C', 'B'): ['Science fiction', 'Us presidents', '20th century'],
        ('C', 'B', 'A', 'A', 'A'): ['Childrens classics', 'Cythulhu mythos', 'rock n roll'],
        ('C', 'B', 'A', 'A', 'B'): ['Nature', 'Brain', 'Pirates'],
        ('C', 'B', 'A', 'A', 'C'): ['Fairytale retellings', 'Christian contemporary fiction', 'Egypt'],
        ('C', 'B', 'A', 'B', 'B'): ['Musicals', 'Denmark', ' 4th century'],
        ('C', 'B', 'A', 'B', 'A'): ['Comics manga', 'foodie', 'tarot'],
        ('C', 'B', 'A', 'B', 'C'): ['Politics', 'The united states of america', 'archaelogy'],
        ('C', 'B', 'A', 'C', 'C'): ['Entrepreneurship', 'Naturopathy', 'The world'],
        ('C', 'B', 'A', 'C', 'A'): ['Stories', 'lds fiction', 'amish fiction'],
        ('C', 'B', 'A', 'C', 'B'): ['Futuristic', 'Legal thriller', 'internet'],
        ('C', 'B', 'B', 'A', 'A'): ['Mysticism', 'Magical realism', 'New weird'],
        ('C', 'B', 'B', 'A', 'B'): ['Surreal', 'Adoption', 'Animals'],
        ('C', 'B', 'B', 'A', 'C'): ['Literature', 'Vampires', 'Cartography'],
        ('C', 'B', 'B', 'B', 'B'): ['Fantasy', 'Games', 'Christian living'],
        ('C', 'B', 'B', 'B', 'A'): ['Chapter books', 'Harlequin nocturne', 'Drawing'],
        ('C', 'B', 'B', 'B', 'C'): ['Poetry plays', 'Quantum mechanics', 'Banks'],
        ('C', 'B', 'B', 'C', 'C'): ['Mystery', 'Fandom', 'Polish literature'],
        ('C', 'B', 'B', 'C', 'A'): ['Young adult contemporary', 'book club', 'Musicians'],
        ('C', 'B', 'B', 'C', 'B'): ['Historical romance', 'Eastern Africa', 'Wilderness'],
        ('C', 'B', 'C', 'A', 'A'): ['Romanticism', 'Tv', 'Holiday'],
        ('C', 'B', 'C', 'A', 'B'): ['Social justice', 'Wicca', 'Teen'],
        ('C', 'B', 'C', 'A', 'C'): ['Criticism', 'Engineering', 'Metaphysics'],
        ('C', 'B', 'C', 'B', 'B'): ['Victorian romance', 'Young readers', 'Museums'],
        ('C', 'B', 'C', 'B', 'A'): ['Storytime', 'Thelema', 'Weird fiction'],
        ('C', 'B', 'C', 'B', 'C'): ['World history', 'Naval history', 'Historical'],
        ('C', 'B', 'C', 'C', 'C'): ['Diary', 'Recreation', 'American'],
        ('C', 'B', 'C', 'C', 'A'): ['Light novel', 'Music', 'Words'],
        ('C', 'B', 'C', 'C', 'B'): ['European literature', 'Terrorism', 'Cyberpunk'],
        ('C', 'B', 'C', 'A', 'A'): ['Choose your own adventure', 'Holland', 'Canon'],
        ('C', 'B', 'C', 'A', 'B'): ['Contemporary romance', 'demons', 'marvel'],
        ('C', 'B', 'C', 'A', 'C'): ['Cults', 'Paranormal urban fantasy', 'Civil war eastern theater'],
        ('C', 'B', 'C', 'B', 'B'): ['Turkish literature', 'Bulgarian literature', 'Traditional chinese medicine'],
        ('C', 'B', 'C', 'B', 'A'): ['True story', 'Planetary romance', 'Fables'],
        ('C', 'B', 'C', 'B', 'C'): ['Social movements', 'Urban planning', 'Feminist theory'],
        ('C', 'B', 'C', 'C', 'C'): ['Essays', 'Numerology', 'Geometry'],
        ('C', 'B', 'C', 'C', 'A'): ['Modern classics', 'Category romance', 'Japan'],
        ('C', 'B', 'C', 'C', 'B'): ['History', 'Belgian', 'Christian romance'],
        ('C', 'C', 'B', 'A', 'A'): ['Graphic novels manga', 'Spider man', 'Family'],
        ('C', 'C', 'B', 'A', 'B'): ['Social issues', 'Counter culture', 'Bizarro fiction'],
        ('C', 'C', 'B', 'A', 'C'): ['Mental health', 'Greek mythology', 'Art history'],
        ('C', 'C', 'B', 'B', 'B'): ['Nonfiction', 'Theathre', 'Design'],
        ('C', 'C', 'B', 'B', 'A'): ['Realistic fiction', 'Amish', 'Reegency'],
        ('C', 'C', 'B', 'B', 'C'): ['Business', 'Finance', 'Counselling'],
        ('C', 'C', 'B', 'C', 'C'): ['Personal development', 'Music Biography', 'Class'],
        ('C', 'C', 'B', 'C', 'A'): ['Komik', 'Humor', 'Religion'],
        ('C', 'C', 'B', 'C', 'B'): ['Action', 'Biblical fiction', 'Doctor who'],
        ('C', 'C', 'C', 'A', 'A'): ['Alternate Universe', 'Atheism', 'Belief'],
        ('C', 'C', 'C', 'A', 'B'): ['American revolution', 'Spanish civil war', 'Japanese literature'],
        ('C', 'C', 'C', 'A', 'C'): ['Space', 'Puzzles', 'Warriors'],
        ('C', 'C', 'C', 'B', 'B'): ['Classic literature', 'Gaming', 'Prehistory'],
        ('C', 'C', 'C', 'B', 'A'): ['Comedy', 'X men', 'Comix'],
        ('C', 'C', 'C', 'B', 'C'): ['Philosophy', 'Mathematics', ' 6th century'],
        ('C', 'C', 'C', 'C', 'C'): ['Leadership', 'Hard boiled', 'Hard science fiction'],
        ('C', 'C', 'C', 'C', 'A'): ['Folk tales', 'Superheroes', 'Writing'],
        ('C', 'C', 'C', 'C', 'B'): ['Activism', 'Money management', 'Soldiers'],
    }
    possible_combinations = itertools.product('ABC', repeat=len(scoresLetter))

    for combination in possible_combinations:
        if all(combination[i] == scoresLetter[i] for i in range(len(scoresLetter))):
            return rf.randomForest((book_categories[combination]),rate)
